"""Export a complete, human-inspectable research dossier.

Produces JSON + Markdown + a manifest with SHA-256 hashes so a third party can
verify integrity. Export is local-only and requires human review (publication policy).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..core.clock import now_iso
from ..core.hashing import hash_json, hash_text
from ..epistemology.types import EntityType
from .service import ResearchLedger


def build_dossier(ledger: ResearchLedger, project_id: str) -> dict[str, Any]:
    project = ledger.get_project(project_id)
    if project is None:
        raise ValueError(f"Project {project_id} not found")
    entities = ledger.list_entities(project_id)
    provenance = ledger.provenance_for_project(project_id)
    by_type: dict[str, list[dict[str, Any]]] = {}
    for e in entities:
        by_type.setdefault(e["type"], []).append(e)
    return {
        "acero_version": "0.4.0",
        "exported_at": now_iso(),
        "project": project.model_dump(),
        "counts": {t: len(v) for t, v in sorted(by_type.items())},
        "entities": entities,
        "entities_by_type": by_type,
        "provenance": provenance,
    }


def _dossier_markdown(dossier: dict[str, Any]) -> str:
    p = dossier["project"]
    lines = [
        f"# Dossier: {p['title']}",
        "",
        f"- **Project ID:** `{p['id']}`",
        f"- **Domain:** {p['domain']}",
        f"- **Exported:** {dossier['exported_at']}",
        f"- **ACERO version:** {dossier['acero_version']}",
        "",
        "> Generated by ACERO. ACERO is not an author. Requires human review before any use.",
        "",
        "## Entity counts",
        "",
    ]
    for t, n in dossier["counts"].items():
        lines.append(f"- {t}: {n}")
    order = [
        EntityType.QUESTION, EntityType.ASSUMPTION, EntityType.HYPOTHESIS,
        EntityType.PREDICTION, EntityType.EXPERIMENT, EntityType.RESULT,
        EntityType.NEGATIVE_RESULT, EntityType.EVIDENCE, EntityType.COUNTEREVIDENCE,
        EntityType.CLAIM, EntityType.OPEN_QUESTION,
    ]
    by_type = dossier["entities_by_type"]
    for et in order:
        items = by_type.get(et.value, [])
        if not items:
            continue
        lines += ["", f"## {et.value}", ""]
        for it in items:
            lines.append(f"### {it['title']}  `({it['id']})`")
            lines.append(f"- state: {it['state']} · confidence: {it.get('confidence')}")
            if it.get("description"):
                lines.append(f"- {it['description']}")
            if it.get("provenance"):
                lines.append(f"- provenance refs: {len(it['provenance'])}")
            lines.append("")
    lines += ["", f"## Provenance events ({len(dossier['provenance'])})", ""]
    for ev in dossier["provenance"]:
        lines.append(f"- `{ev['at']}` **{ev['action']}** by {ev['actor']}: {ev['summary']}")
    return "\n".join(lines) + "\n"


def export_project(
    ledger: ResearchLedger, project_id: str, out_dir: str | Path
) -> dict[str, str]:
    """Write dossier.json, dossier.md, and manifest.json (with hashes). Returns paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dossier = build_dossier(ledger, project_id)

    json_text = json.dumps(dossier, indent=2, ensure_ascii=False)
    md_text = _dossier_markdown(dossier)

    (out / "dossier.json").write_text(json_text, encoding="utf-8")
    (out / "dossier.md").write_text(md_text, encoding="utf-8")

    manifest = {
        "project_id": project_id,
        "exported_at": dossier["exported_at"],
        "files": {
            "dossier.json": hash_text(json_text),
            "dossier.md": hash_text(md_text),
        },
        "dossier_hash": hash_json(dossier),
    }
    (out / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (out / "checksums.txt").write_text(
        "\n".join(f"{h}  {name}" for name, h in manifest["files"].items()) + "\n",
        encoding="utf-8",
    )
    return {
        "dir": str(out),
        "json": str(out / "dossier.json"),
        "markdown": str(out / "dossier.md"),
        "manifest": str(out / "manifest.json"),
    }
