"""Levels of independence — a cross-check is not automatically independence.

The reviewer: two scripts can differ and still share the same conceptual error (same
wrong definition, same leakage, same contaminated variable, both generated by the same
model+prompt, same buggy library). So "verified by a second implementation" must be
graded, not assumed.

    Level 0  reejecución idéntica
    Level 1  mismo algoritmo, otra implementación
    Level 2  otro lenguaje o librería
    Level 3  otro método estadístico que estima el mismo fenómeno
    Level 4  otro dataset o cohorte independiente
    Level 5  otro equipo/agente sin acceso al análisis original
    Level 6  replicación externa humana

A positive exploratory result must NOT be promoted much by a Level-1 check. A strong
claim requires at least a methodologically-different implementation (≥ Level 3) AND an
independent dataset (Level 4).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum


class IndependenceLevel(IntEnum):
    IDENTICAL_RERUN = 0
    SAME_ALGO_OTHER_IMPL = 1
    OTHER_LANGUAGE_LIBRARY = 2
    OTHER_STAT_METHOD = 3
    OTHER_DATASET_COHORT = 4
    OTHER_TEAM_OR_AGENT = 5
    EXTERNAL_HUMAN_REPLICATION = 6


_LABELS = {
    0: "reejecución idéntica", 1: "mismo algoritmo, otra implementación",
    2: "otro lenguaje o librería", 3: "otro método estadístico (mismo fenómeno)",
    4: "otro dataset o cohorte", 5: "otro equipo/agente sin acceso",
    6: "replicación externa humana",
}


def label(level: IndependenceLevel | int) -> str:
    return _LABELS.get(int(level), "?")


@dataclass
class IndependenceCheck:
    level: IndependenceLevel
    description: str
    agreed: bool                 # did the independent check AGREE with the result?


class EvidenceStrength(IntEnum):
    NONE = 0
    WEAK = 1        # only re-run / same-algo agreement
    MODERATE = 2    # different method OR independent dataset (one, not both)
    STRONG = 3      # different method AND independent dataset both agree


@dataclass
class IndependenceLedger:
    """Collects the independence checks a result has survived."""
    checks: list[IndependenceCheck] = field(default_factory=list)

    def add(self, level: IndependenceLevel, description: str, agreed: bool
            ) -> IndependenceCheck:
        c = IndependenceCheck(level, description, agreed)
        self.checks.append(c)
        return c

    def _agreed_at_or_above(self, level: int) -> bool:
        return any(c.agreed and int(c.level) >= level for c in self.checks)

    def max_agreed_level(self) -> int:
        agreed = [int(c.level) for c in self.checks if c.agreed]
        return max(agreed) if agreed else -1

    def strength(self) -> EvidenceStrength:
        method_diff = self._agreed_at_or_above(IndependenceLevel.OTHER_STAT_METHOD)
        indep_data = self._agreed_at_or_above(IndependenceLevel.OTHER_DATASET_COHORT)
        if method_diff and indep_data:
            return EvidenceStrength.STRONG
        if method_diff or indep_data:
            return EvidenceStrength.MODERATE
        if any(c.agreed for c in self.checks):
            return EvidenceStrength.WEAK
        return EvidenceStrength.NONE

    def has_independent_dataset(self) -> bool:
        return self._agreed_at_or_above(IndependenceLevel.OTHER_DATASET_COHORT)

    def summary(self) -> dict[str, object]:
        return {
            "strength": self.strength().name.lower(),
            "max_agreed_level": self.max_agreed_level(),
            "max_agreed_label": label(self.max_agreed_level())
                if self.max_agreed_level() >= 0 else "ninguno",
            "independent_dataset": self.has_independent_dataset(),
            "n_checks": len(self.checks),
        }
