"""Plural adversarial panel — replace the single critic with incompatible mandates.

The reviewer: one adversarial agent (Aristóteles), generated by related models, can share
the investigator's blind spots and create a false sense of rigor. So oppose the result
from several INCOMPATIBLE angles, and — crucially — DO NOT seek premature consensus:
preserve disagreement as signal.

This module is the framework: eight panelists with fixed mandates, a structured review
model, and an aggregation that (a) lets any hard-mandate panelist BLOCK, and (b) reports
the spread of verdicts rather than averaging it away. The actual opinions come from an
injected `reviewer_fn` (the real one calls Codex with each persona; tests inject
deterministic reviews), keeping the governance logic pure and testable.

Aristóteles is not removed — he becomes one voice (the Hostile Writer / generalist) in a
panel that no longer pretends a single sceptic is enough.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum


class Panelist(str, Enum):
    STATISTICIAN = "estadístico"
    CAUSALIST = "causalista"
    DOMAIN_EXPERT = "experto_dominio"
    REPLICATOR = "replicador"
    DATA_DETECTIVE = "detective_datos"
    NOVELTY_REVIEWER = "revisor_novedad"
    ALT_MECHANISM = "abogado_mecanismo_alternativo"
    HOSTILE_WRITER = "redactor_hostil"


# each persona's mandate + what it hunts for (fed to Codex in the real integration)
MANDATES: dict[Panelist, dict[str, object]] = {
    Panelist.STATISTICIAN: {"mandate": "rigor estadístico",
        "looks_for": ["multiplicidad", "potencia insuficiente", "intervalos engañosos",
                      "supuestos violados", "selección de modelo", "stopping adaptativo",
                      "pseudorreplicación"]},
    Panelist.CAUSALIST: {"mandate": "validez causal",
        "looks_for": ["confusión", "colisionadores", "causalidad inversa",
                      "error del estimando", "extrapolación fuera de población"]},
    Panelist.DOMAIN_EXPERT: {"mandate": "plausibilidad del dominio",
        "looks_for": ["variables imposibles", "unidades incorrectas", "instrumentos",
                      "condiciones experimentales", "conocimiento tácito no capturado"]},
    Panelist.REPLICATOR: {"mandate": "reproducir sin leer la narrativa",
        "looks_for": ["no reproducible", "dependencia del análisis original"]},
    Panelist.DATA_DETECTIVE: {"mandate": "integridad de datos",
        "looks_for": ["duplicados", "contaminación", "etiquetas incorrectas",
                      "batch effects", "cambios de versión", "fuga", "valores imposibles"]},
    Panelist.NOVELTY_REVIEWER: {"mandate": "demostrar que ya existe",
        "looks_for": ["afirmación previa equivalente", "resultado en otra terminología"]},
    Panelist.ALT_MECHANISM: {"mandate": "proponer ≥3 modelos incompatibles",
        "looks_for": ["explicación alternativa 1", "explicación alternativa 2",
                      "explicación alternativa 3"]},
    Panelist.HOSTILE_WRITER: {"mandate": "el abstract excede los resultados",
        "looks_for": ["sobreafirmación", "lenguaje causal indebido", "generalización"]},
}

# panelists whose blocking objection HALTS advancement (hard scientific gates)
HARD_MANDATE = frozenset({Panelist.STATISTICIAN, Panelist.CAUSALIST,
                          Panelist.DATA_DETECTIVE})

VERDICTS = ("solido", "prometedor", "debil", "defectuoso")
_RANK = {"solido": 3, "prometedor": 2, "debil": 1, "defectuoso": 0}


@dataclass
class Review:
    panelist: Panelist
    verdict: str                      # one of VERDICTS
    objections: list[str] = field(default_factory=list)
    blocking: bool = False
    note: str = ""


ReviewerFn = Callable[[Panelist, dict], Review]


@dataclass
class PanelVerdict:
    reviews: list[Review]

    @property
    def verdicts(self) -> dict[str, str]:
        return {r.panelist.value: r.verdict for r in self.reviews}

    @property
    def distinct_verdicts(self) -> set[str]:
        return {r.verdict for r in self.reviews}

    @property
    def consensus(self) -> bool:
        """Only a real consensus if EVERY panelist agrees — else 'en disputa'."""
        return len(self.distinct_verdicts) == 1

    @property
    def disagreement(self) -> int:
        return len(self.distinct_verdicts)

    def blocking_objections(self) -> list[Review]:
        return [r for r in self.reviews if r.blocking]

    def hard_blocks(self) -> list[Review]:
        """Blocking objections from a HARD-mandate panelist — these halt advancement."""
        return [r for r in self.reviews
                if r.blocking and r.panelist in HARD_MANDATE]

    def blocked(self) -> bool:
        return bool(self.hard_blocks())

    def worst_verdict(self) -> str:
        return min((r.verdict for r in self.reviews), key=lambda v: _RANK.get(v, 0),
                   default="defectuoso")

    def summary(self) -> dict[str, object]:
        return {
            "consensus": self.consensus,
            "status": "consenso" if self.consensus else "en disputa",
            "disagreement": self.disagreement,
            "worst_verdict": self.worst_verdict(),
            "blocked": self.blocked(),
            "hard_blocks": [r.panelist.value for r in self.hard_blocks()],
            "verdicts": self.verdicts,
            "n_objections": sum(len(r.objections) for r in self.reviews),
        }


def run_panel(context: dict, reviewer_fn: ReviewerFn,
              panelists: list[Panelist] | None = None) -> PanelVerdict:
    """Ask each panelist independently; NEVER force agreement. Disagreement is kept."""
    members = panelists or list(Panelist)
    reviews = [reviewer_fn(p, context) for p in members]
    return PanelVerdict(reviews)
